[CmdletBinding(SupportsShouldProcess)]
param([Parameter(Mandatory)][ValidateSet('1.0.0')][string]$FromVersion,[ValidateSet('Auto','Laptop','Desktop')][string]$Role='Auto',[switch]$PreviewOnly)
$ErrorActionPreference='Stop';$here=Split-Path -Parent $MyInvocation.MyCommand.Path;Import-Module (Join-Path $here 'windows\DevFleet.Common.psm1') -Force;Assert-PowerShell7;Assert-Administrator
$state=Get-DevFleetStateRoot;$configPath=Join-Path $state 'devfleet.config.json';if(-not(Test-Path $configPath)){throw 'No installed DevFleet configuration found.'};$old=Get-Content $configPath -Raw|ConvertFrom-Json;$schema=[int]$old.SchemaVersion;$version=[string]$old.PackageVersion;$isV10=($schema -eq 1 -and ([string]::IsNullOrWhiteSpace($version) -or $version -eq '1.0.0'));$isV11=($schema -eq 2 -and $version -eq '1.1.0');if(-not($isV10 -or $isV11)){throw "Unsupported source schema/package: $schema/$version"};$label=if($isV10){'v1.0.0'}else{'v1.1.0-rerun'};$stamp=(Get-Date).ToString('yyyyMMdd-HHmmss');$backup=Join-Path $state "upgrade-backups\$label-$stamp";New-Item -ItemType Directory $backup -Force|Out-Null;Copy-Item $configPath (Join-Path $backup 'devfleet.config.json');foreach($n in @('secrets','exports')){if(Test-Path(Join-Path $state $n)){Copy-Item (Join-Path $state $n) (Join-Path $backup $n) -Recurse -Force}};if(Test-Path(Join-Path $state 'package-root.txt')){Copy-Item (Join-Path $state 'package-root.txt') $backup}
& (Join-Path $here 'windows\Migrate-Config.ps1') -ConfigPath $configPath -OutputPath $configPath -PreviewOnly;if($PreviewOnly){Write-Host "Preview complete. Backup: $backup";return}
$instances=Get-MultipassInstances;$localNames=@($instances|ForEach-Object name);$targets=@();foreach($n in @([string]$old.Primary.InstanceName,[string]$old.Failover.InstanceName,[string]$old.Vault.InstanceName)){if($n -and $n -in $localNames){$targets+=$n}}
foreach($n in $targets){New-DevFleetSnapshotSafe -InstanceName $n -SnapshotName "pre-v1-1-0-$stamp"|Out-Null}
& (Join-Path $here 'windows\Migrate-Config.ps1') -ConfigPath $configPath -OutputPath $configPath -Confirm:$false;Protect-DevFleetStateAcl;Set-Content (Join-Path $state 'package-root.txt') $here -Encoding utf8;$config=Get-DevFleetConfig
if($config.Primary.InstanceName -in $localNames){& (Join-Path $here 'windows\02-Provision-ComputeNode.ps1') -NodeRole Primary};if($config.Failover.InstanceName -in $localNames){& (Join-Path $here 'windows\02-Provision-ComputeNode.ps1') -NodeRole Failover};if($config.Vault.InstanceName -in $localNames){& (Join-Path $here 'windows\03-Provision-Vault.ps1')}
$local=if($config.Primary.InstanceName -in $localNames){$config.Primary.InstanceName}elseif($config.Failover.InstanceName -in $localNames){$config.Failover.InstanceName}else{$null};if($local){& (Join-Path $here 'windows\08-Install-Shortcuts.ps1') -LocalInstanceName $local};if($Role -eq 'Laptop' -or ($Role -eq 'Auto' -and $config.Failover.InstanceName -in $localNames)){try{& (Join-Path $here 'client\Configure-SSH.ps1') -SkipConnectivityTest}catch{Write-Warning $_};try{& (Join-Path $here 'client\Configure-VSCode.ps1') -ExtensionSets core}catch{Write-Warning $_}}
& (Join-Path $here 'windows\Test-DevFleet.ps1') -AllLocalInstances;[ordered]@{From=$label;To='1.1.0';Completed=(Get-Date).ToString('o');StateBackup=$backup;Snapshots=$targets;Preserved='VMs, projects, Git repositories, both Docker stores, volumes, credentials, restic snapshots, vault data, Tailscale identities, SSH keys, dashboard credentials, pairing, quarantine and custom configuration'}|ConvertTo-Json -Depth 10|Set-Content (Join-Path $backup 'upgrade-result.json') -Encoding utf8;Write-Host "DevFleet v1.1.0 upgrade complete. Recovery: $backup" -ForegroundColor Green
